### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by magaton** [adam-cowley/graphapp-starter-react#2]
Hello, I cloned the repo and built from master:
- yarn build
- yarn start

I have latest yarn.

app is available at 3001, because I am locally running grafana.
I am able to connect to my neo4j instance (running inside Neo4jDesktop) using my safari browser.
I am getting white screen with the following text:
MATCH (n) RETURN count(n) AS count
There are 29457 nodes in the database.
And nothing else. What could be the problem?
Thanks.

**Comment by adam-cowley** [comment]
This is just a starter kit with a basic app that shows the database count to start with.  You can start to build your application by editing [App.jsx](https://github.com/adam-cowley/graphapp-starter-react/blob/main/src/App.tsx).

What were you expecting to see?

**Comment by magaton** [comment]
Basically what is at http://charts.graphapp.io/
There, btw I have a problem setting the default database, so in query explorer, the incorrect one is introspected.

**Comment by adam-cowley** [comment]
You can find the code for the Charts app at https://github.com/neo4j-labs/charts

**Comment by magaton** [comment]
great, cloned charts, built everything, and started, but no login form is displayed.
I can create dashboard, but queries & reports obviously don't work throwing client auth failure.
What could be a problem?

**Comment by adam-cowley** [comment]
If you aren't seeing a login screen then it's taking the driver configuration in .env and [passing a driver instance to `Neo4jProvider` in index.tsx](https://github.com/neo4j-labs/charts/blob/main/src/index.tsx#L45). 

Do you have `REACT_APP_NEO4J_SCHEME` in .env?

**Comment by magaton** [comment]
no, but I figured out that I need to edit index.tsx. Thanks

**Comment by magaton** [comment]
No issue. Thanks for help!
